"use client";

import Link from "next/link";
import { usePathname } from "next/navigation";
import { useState } from "react";
// import "./styles.css";

const navLinks = [
  { name: "Register", href: "/register" },
  { name: "Login", href: "/login" },
  { name: "Forgot Password", href: "/forgot-password" },
];

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [input, setInput] = useState("")
  const pathname = usePathname();

  return (
    <div>
      <div>
        <input value={input} onChange={e => setInput(e.target.value)}/>
      </div>
      <nav className="mb-6">
        {navLinks.map((link) => {
          const isActive =
            pathname === link.href ||
            (pathname.startsWith(link.href) && link.href !== "/");

          return (
            <Link
              key={link.name}
              href={link.href}
              className={
                isActive
                  ? "font-bold mr-4 text-blue-500"
                  : "text-gray-600 mr-4 hover:text-blue-400"
              }
            >
              {link.name}
            </Link>
          );
        })}
      </nav>
      <main>{children}</main>
    </div>
  );
}



































// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function AuthLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
        
//         {children}
        
//         <footer
//         style={{
//           backgroundColor: "ghostwhite",
//           padding: "1rem",
//         }}
//         >
//           <p>Footer</p>
//         </footer>
//         </body>
//     </html>
//   )
// }
